server:
  port: 8040 #修改端口
spring:
  application:
    name: springcloud-order-service-auth #修改名字
  jpa: 
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                           # 指定数据源
    platform: h2                        # 指定数据源类型
    schema: classpath:order_schema.sql        # 指定h2数据库的建表脚本
    data: classpath:order_data.sql            # 指定h2数据库的数据脚本
logging:                                # 配置日志级别，让hibernate打印出执行的SQL
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

eureka:
  client:
    serviceUrl: 
      defaultZone: http://shuyuq:shuyuq123@localhost:8761/eureka/