server:
  port: 8050 #设置端口号
spring:
  application:
    name: springcloud-user-service-auth
eureka: 
  client: 
    service-url:
      defaultZone: http://shuyuq:shuyuq123@localhost:8761/eureka/