security:
  basic:
    enabled: true #开启基于HTTP的安全验证
  user:
    name: shuyuq
    password: shuyuq123

server: 
  port: 8761                    # 指定该Eureka实例的端口,默认为8761
eureka:
  client:
    registerWithEureka: false  
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:${server.port}/eureka